### ISSUE TITLE
Segmentation fault in modsecurity.c after upgrade to httpd-2.4.6-40

### ISSUE THREAD

**Issue by magicdude4eva** [SpiderLabs/ModSecurity#1033]
Updated from httpd-2.4.6-31.el7.centos.1.x86_64  to httpd-2.4.6-40.el7.centos.x86_64  and now receive the following segmentation faults:

```
Core was generated by `/usr/sbin/httpd -DFOREGROUND'.
Program terminated with signal 11, Segmentation fault.
#0  apr_table_addn (t=0x7f606e33e298, key=0x0, val=val@entry=0x7f606e34bff0 "\003") at tables/apr_tables.c:820
820	    hash = TABLE_HASH(key);
(gdb) where
#0  apr_table_addn (t=0x7f606e33e298, key=0x0, val=val@entry=0x7f606e34bff0 "\003") at tables/apr_tables.c:820
#1  0x00007f60641d5233 in msre_action_ctl_execute (msr=0x7f606e3379f8, mptmp=<optimized out>, rule=<optimized out>, action=<optimized out>) at re_actions.c:1266
#2  0x00007f60641c5fce in msre_perform_nondisruptive_actions (msr=msr@entry=0x7f606e3379f8, rule=rule@entry=0x7f606d6c91f8, mptmp=mptmp@entry=0x7f606e3402a8, actionset=<optimized out>) at re.c:2419
#3  0x00007f60641c9a8b in execute_operator (var=var@entry=0x7f606e3409f0, rule=rule@entry=0x7f606d6c91f8, msr=msr@entry=0x7f606e3379f8, acting_actionset=acting_actionset@entry=0x7f606d6d1038, mptmp=mptmp@entry=0x7f606e3402a8) at re.c:2673
#4  0x00007f60641cac2c in msre_rule_process_normal (msr=<optimized out>, rule=0x7f606d6c91f8) at re.c:3202
#5  msre_rule_process (msr=<optimized out>, rule=0x7f606d6c91f8) at re.c:3283
#6  msre_ruleset_process_phase (ruleset=<optimized out>, msr=msr@entry=0x7f606e3379f8) at re.c:1707
#7  0x00007f60641e7348 in modsecurity_process_phase_request_body (msr=0x7f606e3379f8) at modsecurity.c:545
#8  modsecurity_process_phase (msr=msr@entry=0x7f606e3379f8, phase=phase@entry=2) at modsecurity.c:791
#9  0x00007f60641bdca2 in hook_request_late (r=<optimized out>) at mod_security2.c:962
#10 0x00007f606b7c48b0 in ap_run_fixups (r=r@entry=0x7f606e336200) at request.c:83
#11 0x00007f606b7c7482 in ap_process_request_internal (r=r@entry=0x7f606e336200) at request.c:347
#12 0x00007f606b7e2b28 in ap_process_async_request (r=r@entry=0x7f606e336200) at http_request.c:315
#13 0x00007f606b7e2e14 in ap_process_request (r=r@entry=0x7f606e336200) at http_request.c:363
#14 0x00007f606b7df7a2 in ap_process_http_sync_connection (c=0x7f606e3303c0) at http_core.c:190
#15 ap_process_http_connection (c=0x7f606e3303c0) at http_core.c:231
#16 0x00007f606b7d7840 in ap_run_process_connection (c=c@entry=0x7f606e3303c0) at connection.c:41
#17 0x00007f606b7d7c28 in ap_process_connection (c=c@entry=0x7f606e3303c0, csd=<optimized out>) at connection.c:202
#18 0x00007f60671ea80f in child_main (child_num_arg=child_num_arg@entry=3) at prefork.c:707
#19 0x00007f60671eaa55 in make_child (s=0x7f606d58f320, slot=slot@entry=3) at prefork.c:810
#20 0x00007f60671eaab6 in startup_children (number_to_start=2) at prefork.c:828
#21 0x00007f60671eb7c0 in prefork_run (_pconf=<optimized out>, plog=0x7f606d593358, s=0x7f606d58f320) at prefork.c:986
#22 0x00007f606b7b45ae in ap_run_mpm (pconf=pconf@entry=0x7f606d566138, plog=0x7f606d593358, s=0x7f606d58f320) at mpm_common.c:96
#23 0x00007f606b7adb36 in main (argc=2, argv=0x7fffb5aab3e8) at main.c:777
```

**Comment by zimmerle** [comment]
Hi @magicdude4eva,

Did you had the chance to recompile ModSecurity after upgrade Apache? there are any "mis-version" detected during ModSecurity startup messages?
