### ISSUE TITLE
Segmentation faults with Apache >= 2.4.16 (mpm_event)

### ISSUE THREAD

**Issue by TobiasGrave** [SpiderLabs/ModSecurity#1265]
I am getting random segmentation faults when using Apache 2.4 (mpm_event) with Modsecurity. These errors only occur when I load the ModSecurity module, without ModSecurity Apache works fine. The segmentation faults occur even if I remove all rules or disable ModSecurity (`SecRuleEngine off`), so it's not a configuration or ruleset related problem.

I am using the latest version of Apache (2.4.23) and ModSecurity (1.9.1), I have also tried to downgrade ModSecurity to version 1.9 and 1.8 without success.

gdb stack trace:
```
Core was generated by `/usr/sbin/apache24'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000049c427 in event_post_read_request (r=0x7fc9a84bf420) at event.c:995

(gdb) thread apply 1 bt

Thread 1 (Thread 0x7fc99afed700 (LWP 12058)):
#0  0x000000000049c427 in event_post_read_request (r=0x7fc9a84bf420) at event.c:995
#1  0x000000000043a210 in ap_run_post_read_request (r=0x7fc9a84bf420) at protocol.c:2014
#2  0x0000000000477668 in internal_internal_redirect (new_uri=<optimized out>, r=0x7fc9a86fd0a0) at http_request.c:632
#3  0x0000000000476db6 in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:717
#4  0x0000000000495296 in handler_redirect (r=0x7fc9a86fd0a0) at mod_rewrite.c:5184
#5  0x000000000044f4a0 in ap_run_handler (r=0x7fc9a86fd0a0) at config.c:170
#6  0x000000000044f9e9 in ap_invoke_handler (r=r@entry=0x7fc9a86fd0a0) at config.c:434
#7  0x0000000000477a4a in ap_process_async_request (r=0x7fc9a86fd0a0) at http_request.c:410
#8  0x0000000000474161 in ap_process_http_async_connection (c=0x7fc9ae845348) at http_core.c:154
#9  ap_process_http_connection (c=0x7fc9ae845348) at http_core.c:248
#10 0x0000000000458fb0 in ap_run_process_connection (c=0x7fc9ae845348) at connection.c:42
#11 0x000000000049ee2e in process_socket (my_thread_num=25, my_child_num=4, cs=0x7fc9ae8452b8, sock=<optimized out>, p=<optimized out>, thd=<optimized out>) at event.c:1097
#12 worker_thread (thd=<optimized out>, dummy=<optimized out>) at event.c:2001
#13 0x00007fc9b4463184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#14 0x00007fc9b418d37d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
The segmentation faults occur in the `event_post_read_request` hook which has been added to mpm_event in Apache version 2.4.16, they disappear when I downgrade to Apache 2.4.12.

**Comment by TobiasGrave** [comment]
I am no longer sure if this is really caused by ModSecurity, it's possibly a multi threading race condition caused by another Apache module that somehow only occurs when ModSecurity is present too.
