### ISSUE TITLE
ModSecurity 2.7.4 mlogc utilizing 100% CPU

### ISSUE THREAD

**Issue by craiglawson** [SpiderLabs/ModSecurity#129]
I have a recently installed reverse proxy deployed WAF installed running 2.7.4 using mlogc sending logs to a central AuditConsole server. We use the atomicorp commercial rules, hardware spec is as follows: dual quad core Xeon CPU, 32GB RAM, CentOs 6.4 64-bit.

Today, the web apps being protected by the WAF went down and after looking at the reverse proxy I could see mlogc running at 100% on a single CPU core, after running "ps aux | grep mlogc" I could see 2 instances running. I issued the command "kill 1983" as 1983 was the process utilizing 100%. This did not work, so I issued the command "kill -9 1983" which was successful. I am keeping a very close eye on this now
# httpd -v

Server version: Apache/2.2.15 (Unix)
Server built:   May 13 2013 22:11:16
# /opt/modsecurity/bin/mlogc -v

ModSecurity Log Collector (mlogc) v2.7.4
   APR: compiled="1.3.9"; loaded="1.3.9"
  PCRE: compiled="7.8"; loaded="7.8 2008-09-05"
  cURL: compiled="7.19.7"; loaded="libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

Can I provide any further details to help assist? All configuration other than CollectorRoot and LogstorageDir  and the sensor credentials are default in mlogc.conf

Thanks,

Craig

**Comment by celesteking** [comment]
Hello dears. I'm hitting the same problem now. 

```
(gdb) bt
#0  0x00002b533e63316f in pthread_mutex_unlock () from /lib64/libpthread.so.0
#1  0x00002b533e8659b0 in apr_thread_mutex_unlock () from /usr/local/apache/lib/libapr-1.so.0
#2  0x00002b533e8668ca in apr_pool_destroy () from /usr/local/apache/lib/libapr-1.so.0
#3  0x00002b533e866834 in apr_pool_destroy () from /usr/local/apache/lib/libapr-1.so.0
#4  0x0000000000404069 in create_new_worker (lock=0) at mlogc.c:1796
#5  0x00000000004043b5 in add_entry (
    data=0x6139468 "xxx.com 137.186.96.90 - - [23/May/2015:10:22:26 --0500] \"GET /favicon.ico HTTP/1.1\" 200 0 \"-\" \"-\" VWCbMthWnAEAAE6@H4AAAAC0 \"-\" /nobody/20150523/20150523-1022/20150523-102226-VWCbMthWnAEAAE"..., 
    start_worker=1) at mlogc.c:409
#6  0x00000000004057a4 in receive_loop (argc=2, argv=0x7fffa78118a8) at mlogc.c:2065
#7  main (argc=2, argv=0x7fffa78118a8) at mlogc.c:2306
```

This process is ancient as you might see. The newer one doesn't consume much cpu.
```
4     0 20080     1  29   4 171752  3544 -      RNl  ?        305:09 /usr/local/modsecurity/bin/mlogc /etc/httpd/conf/mlogc.conf
4     0 27756 27755  18   0 171752  3556 pipe_w Sl   ?          0:02 /usr/local/modsecurity/bin/mlogc /etc/httpd/conf/mlogc.conf
```

```
# strace -fx -p 20080              
Process 20080 attached with 3 threads - interrupt to quit
[pid 20261] select(0, NULL, NULL, NULL, {0, 5000} <unfinished ...>
[pid 20260] futex(0x60d8fe0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 20261] <... select resumed> )      = 0 (Timeout)
[pid 20261] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid 20261] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
............
[pid 20261] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid 20261] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
Process 20080 detached
Process 20260 detached
Process 20261 detached
```

```strace -fx -p 20080 2>&1 |grep -v 'select(0'``` produces nothing.

**Comment by celesteking** [comment]
It appears the thread is essentially stuck in:

```
(gdb) next
811             apr_pool_destroy(pool->child);
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
810         while (pool->child)
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
811             apr_pool_destroy(pool->child);
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
810         while (pool->child)
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
811             apr_pool_destroy(pool->child);
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
810         while (pool->child)
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
811             apr_pool_destroy(pool->child);
1: pool->child = (apr_pool_t *) 0x35585c8
(gdb) 
810         while (pool->child)
1: pool->child = (apr_pool_t *) 0x35585c8

(gdb) p *pool->child
$8 = {parent = 0x3575cf8, child = 0x0, sibling = 0x35585c8, ref = 0x3575d00, cleanups = 0x0, free_cleanups = 0x0, allocator = 0x34c65e0, subprocesses = 0x0, abort_fn = 0, user_data = 0x0, tag = 0x0, active = 0x35585a0, 
  self = 0x35585a0, self_first_avail = 0x3558640 "VWEww9hWnAEAADIFOPUAAADu", pre_cleanups = 0x0}
```

```
(gdb) list 811
806
807         /* Destroy the subpools.  The subpools will detach themselve from
808          * this pool thus this loop is safe and easy.
809          */
810         while (pool->child)
811             apr_pool_destroy(pool->child);
812
813         /* Run cleanups */
814         run_cleanups(&pool->cleanups);
815
```

If you need more info, tell me.

**Comment by zimmerle** [comment]
I am assuming that it is no longer a problem, therefore I am closing this issue.
