### ISSUE TITLE
libmodsecurity spinning (unresponsive nginx process)

### ISSUE THREAD

**Issue by lkarsten** [SpiderLabs/ModSecurity#1489]
Hi all.

I've built a standalone nginx installation with libmodsecurity and libmodsecurity-nginx. Yesterday evening it went into a tight loop using 100% of a core and stopped responding to requests.

Based on the backtrace from the running process I believe this is a libmodsecurity issue. I'm happy to move this elsewhere if that makes more sense. Please advise.

```# gdb --eval-command="bt" --batch --pid 24543 /opt/nginxmodsec/sbin/nginx

#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:446
#1  0x00007fc94b8ec719 in std::char_traits<char>::move (__n=790174305, __s2=0x7fc8d2811211 "", __s1=0x7fc8d2812211 "") at /build/gcc-6-t_8K6C/gcc-6-6.3.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/char_traits.h:282
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_move (__n=790174305, __s=0x7fc8d2811211 "", __d=0x7fc8d2812211 "") at /build/gcc-6-t_8K6C/gcc-6-6.3.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:309
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace (this=this@entry=0x7fff37f2bfb0, __pos=__pos@entry=227652097, __len1=__len1@entry=0, __s=0x560a639380a0 "\263\311(\311ͱ\343\345\262\311HML\261\263)\311,\311I\265\063\061\060Q\360\313/Qp\313/\315K\261ч\b\332胕", __len2=4096) at /build/gcc-6-t_8K6C/gcc-6-6.3.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:438
#4  0x00007fc94cc42df2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::replace (__n2=<optimized out>, __s=<optimized out>, __n1=0, __pos=227652097, this=0x7fff37f2bfb0) at /usr/include/c++/6/bits/basic_string.h:1688
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::insert (__str=..., __pos1=227652097, this=0x7fff37f2bfb0) at /usr/include/c++/6/bits/basic_string.h:1431
#6  modsecurity::MacroExpansion::expand (input="Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}", rule=rule@entry=0x0, transaction=transaction@entry=0x560a63741420) at macro_expansion.cc:315
#7  0x00007fc94cc4560e in modsecurity::MacroExpansion::expand (input="Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}", transaction=transaction@entry=0x560a63741420) at macro_expansion.cc:47
#8  0x00007fc94cc65bad in modsecurity::actions::LogData::data[abi:cxx11](modsecurity::Transaction*) (this=this@entry=0x560a64117d80, transaction=transaction@entry=0x560a63741420) at actions/log_data.cc:42
#9  0x00007fc94cc4700e in modsecurity::Rule::updateRulesVariable (this=this@entry=0x560a64118060, trans=trans@entry=0x560a63741420) at rule.cc:226
#10 0x00007fc94cc4c592 in modsecurity::Rule::evaluate (this=this@entry=0x560a64118060, trans=trans@entry=0x560a63741420, ruleMessage=std::shared_ptr (count 1, weak 0) 0x560a63933070) at rule.cc:635
#11 0x00007fc94cc40856 in modsecurity::Rules::evaluate (this=0x560a636c3ab0, phase=phase@entry=5, transaction=transaction@entry=0x560a63741420) at rules.cc:212
#12 0x00007fc94cc321f5 in modsecurity::Transaction::processResponseBody (this=0x560a63741420) at transaction.cc:1088
#13 0x00007fc94cc32495 in modsecurity::msc_process_response_body (transaction=<optimized out>) at transaction.cc:1879
#14 0x0000560a61a64a8e in ngx_http_modsecurity_body_filter (r=0x560a63732ac0, in=0x560a63ff9f50) at /home/lkarsten/work/ModSecurity-nginx//src/ngx_http_modsecurity_body_filter.c:164
#15 0x0000560a61a3ebf7 in ngx_http_gzip_body_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/modules/ngx_http_gzip_filter_module.c:452
#16 0x0000560a61a3f55e in ngx_http_postpone_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/ngx_http_postpone_filter_module.c:82
#17 0x0000560a61a41a9b in ngx_http_ssi_body_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/modules/ngx_http_ssi_filter_module.c:411
```

I've rerun the backtrace several times, it is under MacroExpansion::expand every time.

```nginx version: nginx/1.13.2
built by gcc 6.3.0 20170516 (Debian 6.3.0-18)
configure arguments: --add-module=/home/lkarsten/work/ModSecurity-nginx/ --prefix=/opt/nginxmodsec/
```

libmodsecurity from git 65bd06f (master from last week, no related commits since as far as I can tell), libmodsecurity-nginx from git abbf2c4. (latest master). nginx from github mirror, 95dcba6b ostensibly equal to 1.13.2 release.

Ruleset is CRS 3.0. secrulenegine on, body access on, auditlogparts ABIJDFHZ, secauditlogtype serial.

Lengthy full backtrace follows:

```
#2  modsecurity::MacroExpansion::expand (input="Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}", rule=rule@entry=0x0, transaction=transaction@entry=0x560a63741420) at macro_expansion.cc:64
        end = <optimized out>
        variable = "MATCHED_VAR"
        variableValue = <optimized out>
        collection = <optimized out>
        start = 227740658
        res = "Matched Data: user-agent accept-encoding x-forwarded-for x-ua-device host x-varnish found within RESPONSE_BODY: \263\311(\311ͱ\343\345\262\311HML\261\263)\311,\311I\265\063\061\060Q\360\313/Qp\313/\315K\261ч\b\332胕\000\225&\345\247T*$\245'\347\347\344\027\331*\225gd\226\244*\201\214HN\315+I-\262\263\311\060D7\001(b\243\017\225\006\331\005T"...
        pos = 227740658
#3  0x00007fc94cc4560e in modsecurity::MacroExpansion::expand (input="Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}", transaction=transaction@entry=0x560a63741420) at macro_expansion.cc:47
No locals.
#4  0x00007fc94cc65bad in modsecurity::actions::LogData::data[abi:cxx11](modsecurity::Transaction*) (this=this@entry=0x560a64117d80, transaction=transaction@entry=0x560a63741420) at actions/log_data.cc:42
No locals.
#5  0x00007fc94cc4700e in modsecurity::Rule::updateRulesVariable (this=this@entry=0x560a64118060, trans=trans@entry=0x560a63741420) at rule.cc:226
        data = 0x560a64117d80
#6  0x00007fc94cc4c592 in modsecurity::Rule::evaluate (this=this@entry=0x560a64118060, trans=trans@entry=0x560a63741420, ruleMessage=std::shared_ptr (count 1, weak 0) 0x560a63933070) at rule.cc:635
        globalRet = false
        variables = <optimized out>
        recursiveGlobalRet = <optimized out>
        containsDisruptive = false
        finalVars = std::vector of length 0, capacity 0
        eparam = "\"1\""
#7  0x00007fc94cc40856 in modsecurity::Rules::evaluate (this=0x560a636c3ab0, phase=phase@entry=5, transaction=transaction@entry=0x560a63741420) at rules.cc:212
        rule = 0x560a64118060
        i = 27
        rules = std::vector of length -11825327513028, capacity -11825327513028 = {0x560a62fa52b0, 0x560a632058e0, 0x560a632064c0, 0x560a63210bf0, 0x560a6321c330, 0x560a6321cda0, 0x560a632d8a90, 0x560a632eb530, 0x560a63319ca0, 0x560a63328f10, 0x560a6357ac00, 0x560a63583350, 0x560a64021f90, 0x560a6405c150, 0x560a64066fa0, 0x560a640ff1a0, 0x560a6410b4c0, 0x560a6410bf90, 0x560a64110fd0, 0x560a64111bd0, 0x560a641126f0, 0x560a64113b60, 0x560a64114500, 0x560a64115080, 0x560a64115980, 0x560a641165c0, 0x560a641170a0, 0x560a64118060, 0x560a64158930, 0x560a6415a0a0, 0x560a6415b820, 0x560a6415cf90, 0x560a6415e640, 0x560a6415fe70, 0x560a64161480, 0x560a64162be0, 0x560a64168310, 0x560a64169a30, 0x560a6416b130, 0x560a6416ce70, 0x560a6416e830, 0x560a641700e0, 0x560a64171860, 0x560a64172bc0, 0x560a641736e0, 0x560a64174260, 0x560a64174b60, 0x560a641753c0, 0x560a64175e40, 0x560a64176960, 0x560a64177480, 0x560a64178120, 0x560a64178a00, 0x560a64180dd0, 0x560a64184410, 0x41, 0x560a63933c30, 0x560a63933c00, 0x676e697475000001, 0x560a6390f020, 0x560a6390f020, 0x1, 0x676120223122206d, 0x21, 0x560a6390eff8, 0x560a6390eff8, 0x560a63934d90, 0x41, 0x560a63934d30, 0x560a6390f058, 0x3, 0x3a6e6f6900766572, 0x90, 0x560a6390efe0, 0x14d, 0xd1, 0x7fc94c6b6c18 <main_arena+280>, 0x7fc94c6b6c18 <main_arena+280>, 0x676e697475636578, 0x6f74617265706f20, 0x7720227145222072, 0x6172617020687469, 0x676120223122206d, 0x58542074736e6961, 0x7272655f6c71733a, 0x686374616d5f726f, 0x60, 0x70, 0x0, 0x20302e5854203a67, 0x72657375203a6f74, 0x6120746e6567612d, 0x6e652d7470656363, 0x7820676e69646f63, 0x64726177726f662d, 0x7820726f662d6465, 0x697665642d61752d, 0x2074736f68206563, 0x73696e7261762d78, 0x560a63930068, 0xd0, 0x40, 0x560a6392e1a0, 0x560a6390f168, 0x3, 0x560a00766572, 0x560a639333b0, 0x560a63932da0, 0x14d, 0x21, 0x6, 0x0, 0x6c646e656972004c, 0x31, 0x560a6390f1c0, 0x7, 0x64693a454c5552, 0x0, 0x2220666500222072, 0x21, 0x560a6390ecd8, 0x560a6390ecd8, 0x560a6390f190, 0x31, 0x560a6390f210, 0x6, 0x333130303539, 0x0, 0x0, 0x21, 0x560a6390ed98, 0x560a6390ed98, 0x560a63fd4400, 0x41, 0x560a638ee1c0, 0x560a6390f268, 0x2, 0x560a63006469, 0x52417c53454d414e, 0x560a638ee620, 0xcd, 0x31, 0x560a6390f2a0, 0x8, 0x7665723a454c5552, 0x0, 0x52417c53454d414e, 0x41, 0x560a6390f290, 0x560a638ee660, 0x1, 0x560a6390f300, 0x560a6390f300, 0x1, 0xb0, 0x21, 0x560a6390f2d8, 0x560a6390f2d8, 0x560a638ee4e0, 0x41, 0x560a638ee2b0, 0x560a6390f338, 0x3, 0x766572, 0x5b692a5d5e5c225c, 0x560a6390f2c0, 0x14d, 0x21, 0x33, 0x0, 0x0, 0x41, 0x560a6390f5f0, 0x560a6390f570, 0x6e6f697475000001, 0x560a6390f7a0, 0x560a6390f7a0, 0x1, 0x4d587c53006e6f69, 0x31, 0x560a6390f3f0, 0x33, 0x33, 0x0, 0x5d5e5c225c5b762a, 0x41, 0x432065746f6d6552, 0x4520646e616d6d6f, 0x6e6f697475636578, 0x776f646e6957203a, 0x6e616d6d6f432073, 0x7463656a6e492064, 0x6e6f69, 0x31, 0x560a6390f440, 0x8, 0x67736d3a454c5552, 0x560a6358ef00, 0x267c7c5c7c5c7c7c, 0x41...}
#8  0x00007fc94cc321f5 in modsecurity::Transaction::processResponseBody (this=0x560a63741420) at transaction.cc:1088
        bi = <optimized out>
        t = "text/html"
#9  0x00007fc94cc32495 in modsecurity::msc_process_response_body (transaction=<optimized out>) at transaction.cc:1879
No locals.
#10 0x0000560a61a64a8e in ngx_http_modsecurity_body_filter (r=0x560a63732ac0, in=0x560a63ff9f50) at /home/lkarsten/work/ModSecurity-nginx//src/ngx_http_modsecurity_body_filter.c:164
        ret = <optimized out>
        old_pool = 0x0
        buffer_fully_loadead = <optimized out>
        chain = <optimized out>
        ctx = 0x560a63ff9180
#11 0x0000560a61a3ebf7 in ngx_http_gzip_body_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/modules/ngx_http_gzip_filter_module.c:452
        rc = <optimized out>
        flush = <optimized out>
        cl = 0x40
        ctx = 0x560a63ff9bf0
#12 0x0000560a61a3f55e in ngx_http_postpone_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/ngx_http_postpone_filter_module.c:82
        c = 0x560a636c49a0
        pr = <optimized out>
#13 0x0000560a61a41a9b in ngx_http_ssi_body_filter (r=0x560a63732ac0, in=<optimized out>) at src/http/modules/ngx_http_ssi_filter_module.c:411
        len = <optimized out>
        rc = <optimized out>
        b = <optimized out>
        i = <optimized out>
        index = <optimized out>
        cl = <optimized out>
        ll = <optimized out>
        param = <optimized out>
        ctx = 0x0
        mctx = <optimized out>
        bl = <optimized out>
        prm = <optimized out>
        cmd = <optimized out>
        slcf = <optimized out>
        smcf = <optimized out>
        params = {0x560a63741420, 0x194, 0x7fff37f2d460, 0xcf, 0x560a63732ac0, 0x7fc94cc27705 <modsecurity::Transaction::processResponseHeaders(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+309>, 0x7fff37f2d420, 0x3, 0x343034, 0x7fc94cc26882 <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)+146>, 0x560a63732ac0, 0x0, 0x560a63ff9d08, 0x0, 0x0, 0x0, 0x7fff37f2d470}
#14 0x0000560a61a4405c in ngx_http_charset_body_filter (r=0x560a63732ac0, in=0x560a63ff9f30) at src/http/modules/ngx_http_charset_filter_module.c:557
        rc = <optimized out>
        b = <optimized out>
        cl = <optimized out>
        out = 0x560a62f8127a
        ll = <optimized out>
        ctx = 0x0
```

**Comment by zimmerle** [comment]
Hi @lkarsten,

Thank you for the detailed report. I am going to investigate.

**Comment by zimmerle** [comment]
I've made some basic optimizations to avoid the lookup for variables in the replaced content. This optimization may mitigate the issues that you are facing. Still, this macro expansion should be refactored to use the parser variable lookup, during rules load phase, instead of string find/replaces.

The change is available on the following branch:
https://github.com/SpiderLabs/ModSecurity/tree/v3/dev/pull_1489

**Comment by lkarsten** [comment]
Hi. Thanks for looking into it. 
As a data point, I haven't seen this behaviour repeat itself running the same code (with ~daily restarts) for about a week now.

I have testing this commit on my list and will report back with any findings.

**Comment by zimmerle** [comment]
Hi @lkarsten,

Did you had any chance to test this proposed code?

**Comment by lkarsten** [comment]
Hi. I've deployed the branch (on top of current v3/master) to my test system now.

**Comment by zimmerle** [comment]
@lkarsten any problem so far?

**Comment by lkarsten** [comment]
Running nicely. No problems seen.

Please note that this is a test system with very limited traffic (<5k hits per day). I ran some load testing tools against it to try to provoke, but that is of course synthetic traffic.

**Comment by zimmerle** [comment]
Merged into v3/master ;)

**Comment by lkarsten** [comment]
Thank you!
