### ISSUE TITLE
nginx 1.7.4 / modsecurity 2.8.0 reload #2

### ISSUE THREAD

**Issue by ton31337** [SpiderLabs/ModSecurity#801]
Hello @zimmerle,

found another bug after reload is performed. I don't know if you know this already or not. But I think it's somehow related with memory duplication after reload. 

If I perform nginx's reload, website stops working and returns up to 50% of the content by failing to load some images, js, css, etc.

Here is backtrace of coredump:

```
(gdb) bt full
#0  0x00007f0529876031 in ?? ()
No symbol table info available.
#1  0x00000000005372b3 in msre_rule_process_normal (msr=<optimized out>, rule=0x7f051a2c8390) at ../apache2/re.c:3160
        rval = 0x1 <error: Cannot access memory at address 0x1>
        rval_length = -1
        tfnspath = 0x0
        normtab = <optimized out>
        lastvarval = 0x0
        lastvarlen = 0
        tfnchanged = 0
        tarr = 0x7f0529876b38
        telts = <optimized out>
        crec = <optimized out>
        last_crec = <optimized out>

(gdb) handle SIGHUP nostop pass
(gdb) break ../apache2/re.c:3160
(gdb) run

(gdb) print rule->filename
$7 = 0x7f982e5b48c0 "/usr/local/openresty/nginx/conf/waf/websites/stage.conf"
(gdb) print rule->line_num
$8 = 28
```

28 line is:

```
SecRule &TX:ARG_LENGTH "@eq 1" "chain,phase:2,t:none,block,msg:'Argument value too long',id:'960208',ctl:ruleEngine=On,severity:'4',rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'9',tag:'OWASP_CRS/POLICY/SIZE_LIMIT'"
SecRule ARGS "@gt %{tx.arg_length}" "t:none,t:length,setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.notice_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/POLICY/SIZE_LIMIT-%{matched_var_name}=%{matched_var}"
```

Thank you.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
